[build-system]
requires = ["setuptools>=42", "scikit-build>=0.13", "cmake>=3.19"]
build-backend = "setuptools.build_meta"

[project]
name = "pyanime4k"
version = "3.1.0"
license = {text = "MIT"}
requires-python = ">=3.8"
readme = "README.md"
dependencies = ["numpy"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX",
    "Operating System :: Unix",
]

[tool.cibuildwheel]
skip = ["pp*", "*win32", "*i686", "*musllinux*"]
build-verbosity = 2

[tool.cibuildwheel.macos]
repair-wheel-command = "delocate-wheel --library-path lib --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair --extra-library-path lib -w {dest_dir} {wheel}"
