name: Build wheels
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install CUDA
        if: matrix.os == 'windows-latest'
        uses: Jimver/cuda-toolkit@v0.2.23
        id: cuda-toolkit
        with:
          method: 'network'
          sub-packages: '["nvcc", "cudart", "opencl"]'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.12'
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.8'
          CIBW_BUILD_VERBOSITY: '1'
        with:
          output-dir: wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
