name: Build wheels
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Install CUDA (Linux/Windows)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.8'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
